spring:
  application:
    name: client-application
  cloud:    config:      uri: http://localhost:8888
  config:    import: "optional:configserver:"

management:
  endpoints:    web:      base-path: /actuator
      exposure:         include:        - '*'        