
server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:harshalpande/config-env-properties.git
#          username: kkool.harshal@gmail.com
#          password: nT7@zN8@oH8?oJ9#
          default-label: main
          ignore-local-ssh-settings: true
          passphrase: harshal.pande
          private-key: |        
                        -----BEGIN RSA PRIVATE KEY-----
                        Proc-Type: 4,ENCRYPTED
                        DEK-Info: AES-128-CBC,6293BD252D99DDF3A1100FDCB51AFDC9
                        
                        K1AD5Y0EFhbksKMFze1HYfmepnFoAJ/q3T/6NLOkHK2l6TrBSFT8r9bojQVbIG2R
                        ZBi6xGD88ruMKyHL1rSmAX3NXaALI5GhsI6BwnUjjW/EpX0F6OlE2ZluuIGNTQLL
                        fNpy1Cx5QTOSD03Q6wfzi1kRAkb0fiUZZY9pODDW3LMOBoAPrB5Xv1Bo2Yn9dwiw
                        OAu45LP7mRWAgHc2XKEkt0dWHjaKRraBpvQxC1hhhPEGkjKxeedLx2NMJFcE44X1
                        Mk5c+cd13QN8HzP0399pPT1O3RIwk0gkemqhGwkZh30plJ+dMTy0h12JP6uxmJW6
                        iqfk8ZymAnATzysaw6CIo656PToTtzy47lxw/1kLVlhzdcxgZJyV58JPs9POQcMt
                        OG2WIc9PDqZ/+3bDwJLoA1yR/UKEBGgPx6sIzbBxf19SqLxLt14CAENb4v9ngemk
                        DzsAosZPfb1bwJ3zSaUhmhJfa6VLx9byGJoOCBhfnkdK5o5i5/0ehd3DBwXYoIa1
                        YRJSbaqSORpUewQZK9HifLUBPF2f0puqXZNqBODLQ7r6OKjZbfFFXpml3RI0x7aB
                        5HSl7cxw217JTIH9HZy+AfHpUi96Ydt5/bkLgqEOfvMuLuUPAdwXaaKUAZ1J71Qq
                        Mi5BMwIBOyDfe/6G/++notcNrgNJCQHo/+XMG4y1XQtGXqsV6b1JBA/Hn+CVW4HQ
                        DOZUmg0oZdXnDTZiTcUGUj8ESNnM+EQmwJTZhNH7ORDFeH4gGnCOE9/+kYxAss+M
                        9AlSKR6ap0FJjkzZb1vq050qyBi+BxjhQTJdbaP6bbZ2JsO7usnTV2BZ0lu+LwWv
                        u9dYepJ5I4BfrjSt7FQo34LO9Ov4pCSYXeIEfwKHTE71+NBAQEZqk5FwSUJtByO8
                        /OFzji+TNC067bjY4CsgA4Prig0TNbG7PqZfP6WVEOKZFYT24WJkJQgJpJqjFfhS
                        DpAusqm4IDLsUT/PIYADjnCgbVM42aV/JL2GZ96off7LT4H4rAIIS8qY74uMDucq
                        o8zR+vKRl+TruhuJ18uclNCz01SHwPIMgpZtjbhfYtjNCRNyhTXet8kGlkiwuEbo
                        7nRJlWcFoCS5+MmPczM4wrJcjyM4jCMLlLxzoRmokUHAflDJSxT+eSPJDa49fW8K
                        1SBMvOr9deoK4Vf8dJdYdciT/+ASIZgzVQwp9+mTdGVUxxLWSZ0nNomEcwOSQSpP
                        0ExGgCbqftb+pEdJaTMijx0CmX5n0IgAY4MDFpSynL4xHPwG2Xjq4RNePWrSbdxt
                        UMNMBEItR4OFLF49ZiqrMfHpYS+C7VfaUcDztVZUPr/+Qfm5qq7J2fIZiRNEU9Rw
                        W+6QvAwPqzUsquJMQwpDTdOKbABYxz9vmxefTUQQfORz3ufwAuTcF7Yu6xuf8jOq
                        G8sabrOF10ll7J7gFmpyS5mavZEXW+mbxn7CUNrZr84YnGAtEoi4dgHI742PgcWL
                        FaL0A7nZ9AzMh2DAgJo8Qk8ZnnGN7oc9AFFzESMAVoxT7fFlBXD3I//ygrqYlTKI
                        W+U53K22qny3VpILEaowdjX8OS6B5A9i/EkxzYahoNWpY+bpH8DsKgKJcHGlaCrr
                        fQ6ETRjEFEOrx03JLTzHRcVdH3eL52FC4C8/TqgxsceTs0pe2SflA/lrrgYZLpmW
                        xc/NsriRoBg/KyLxwmL0hQ4VbvUJWFXFwnLw1TGVGAY9J4FCDNhyYZgOl0POBM3K
                        6/dITcz8h+alawTzGOEP+ApAKoyORSXAUORw9Xjerf3YQFhcUVV9PvAaMOzaZDWF
                        Upt8XAvk51gguhjqFTJO7SUsOMyhltIQxt4jS48zi53HNrAHvboOD5WPtVaEd07v
                        Hp3G5vunxZnysdLW//RMPykCwXuTtGfnLhWVgaAUlBDeEyIyxaE92Asw98P+mrMV
                        ac/UAcemsb9tDk/2X0VI2Y1CzDdfs+3PSdQJ7+RL9DnF0sE0J1pb9ptZ52ZZTc6A
                        fMWm/4RTomouq8jcsHKCaaE5Xv5xU89K0GeerlnrZ6K0SzbpO6Kwj/sb6PCNt1VK
                        e4j7m3lk7mIbzkm4Q9zPOTyTeFs+b5Q2CmA1YNekAQIH/YHNoIU/RsTcyywOXTI9
                        Vz3fMUe/UUeVaDeNr0LpPD1aCZV3nKEw5iqwolmcww9dOCWqSuboZXMwnVqaRss/
                        4XCgVB+JVFcqK8DW8bUIH9vEdYbdNAJJiovKNtSVEIXaEzQQAKo3TCPsTMzjN9HO
                        Ywb42V5qpptPGpaS4Z99SmcAxpsfX5zq5WebuO+YCBTHy1A8YtrRyMwInobRC7O/
                        3X5oJVY09AiCeeHfp/pAgQ0qeiMJZnE6/KEaqtzb7FMFJTzUtdjp8XIszE+a+eS9
                        eOS8oDtJfSmXgxNkl1RMwKqbODwVelvSd06np7JLoEBjoaSvWBnai5PBaR2+aJzo
                        4Atc1aQqCHr9Ym4rdkp86eY76HClNsbmo0wdVgOHfY1YNZIN+bHqxG4tm1WzPfV6
                        wX6jjFhgUOM+h4lQ4k7+SZkAxRGHbmSdn2yCMrlJw0lLQ/AGjbDQlwtc2SCaYbKC
                        XulohCUSO236TACXPDBIWembdOPMQv6clIAX88F4YLECjEn11khHXd53zTxhGyFX
                        SftPZ6rri1VgD9mONIloJkT6vDnwi+SKuNqeA7diOpKClMVO/z8KAh3cMz2v11EO
                        qRMOb1Kd9hGmXrLeglOeGSIVY4bSsPFrO3LQnkQW/oRTzDLq20mApH6GObrpiVaI
                        9gzuVYV41jYYuooYiyaFd/9v2xaIVAjkjN13a4ELxYCYMxn4FPnl3uAUO6xhusDc
                        tR8Nv4ddw3zZyp6aDLjH6CDY2vGNG7LxaHY7Ffvpy0oX/tfDcjF4atam+4aALE2r
                        crLc1T8kZibitOrlFWpBtRJUU5hF/yOAeS6An4fPdsRJuBhDSWwnERPt4E70SF0d
                        gA3fWrZTQMzAGc981uMXMqW6//Hb2fWx1NGwgSzJOF4d+LoO3LPpB4BSFpzi8vyc
                        xkxuVjFbYFqYjG4HdeWMQ3VEHMvu0io8BoxnNBUPfRt0SpYX58DivJpRYE0DpqSt
                        HgALuS3zcmoGrW69m8f6OCP7g8YRjKjk/cbmkaO0HIZgsfp7uqp2jX55vTRNinxp
                        -----END RSA PRIVATE KEY-----